// <auto-generated />
namespace SuperKidCity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Initials19012017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initials19012017));
        
        string IMigrationMetadata.Id
        {
            get { return "201701191420217_Initials19012017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
